<?php

require_once 'civicaseextras.civix.php';
use CRM_Civicaseextras_ExtensionUtil as E;
use \Civi\Angular\ChangeSet as AngularChangeSet;
use \Civi\Angular\Manager as AngularManager;

/**
 * Implements hook_civicrm_config().
 *
 * @link http://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_config
 */
function civicaseextras_civicrm_config(&$config) {
  _civicaseextras_civix_civicrm_config($config);
}

/**
 * Implements hook_civicrm_install().
 *
 * @link http://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_install
 */
function civicaseextras_civicrm_install() {
  _civicaseextras_civix_civicrm_install();
}

/**
 * Implements hook_civicrm_enable().
 *
 * @link http://wiki.civicrm.org/confluence/display/CRMDOC/hook_civicrm_enable
 */
function civicaseextras_civicrm_enable() {
  _civicaseextras_civix_civicrm_enable();
}

/**
 * Implements hook_civicrm_alterAngular().
 *
 * @link https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_alterAngular/
 */
function civicaseextras_civicrm_alterAngular(AngularManager $angular) {
  $loader = Civi::service('angularjs.loader');
  $loader->addModules(['civicaseextras']);

  _civicaseextras_alterAngular_addVisualAlert($angular);
  _civicaseextras_alterAngular_appendOutcomePanel($angular);
}

/**
 * Implements hook_civicrm_alterContent().
 *
 * @link https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_alterContent/
 */
function civicaseextras_civicrm_alterContent (&$content, $context, $templateName, $form) {
  $isViewingTheCaseAdminForm = get_class($form) === CRM_Admin_Form_Setting_Case::class;

  if ($isViewingTheCaseAdminForm) {
    _civicaseextras_alterContent_addCivicaseAdminSettingsFields($content);
  }
}

/**
 * Implements hook_civicrm_preProcess().
 *
 * @link https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_preProcess/
 */
function civicaseextras_civicrm_preProcess($formName, &$form) {
  if ($formName == 'CRM_Admin_Form_Setting_Case') {
    _civicaseextras_preProcess_addCivicaseAdminSettingsFieldsReference($form);
  }
}

/**
 * Adds extra settings fields to the Civicase Admin Settings form.
 *
 * @param string $content the original form content.
 */
function _civicaseextras_alterContent_addCivicaseAdminSettingsFields (&$content) {
  $settingsTemplateHtml = _civicaseextras_getTemplateContent('CRM/Civicaseextra/Admin/Form/Settings.tpl');

  $doc = phpQuery::newDocumentHTML($content);
  $doc->find('table.form-layout-compressed tr:last')->append($settingsTemplateHtml);

  $content = $doc->getDocument();
}

/**
 * It adds extra settings to the Civicase settings page.
 *
 * @param object $form a reference to the civicase admin form.
 */
function _civicaseextras_preProcess_addCivicaseAdminSettingsFieldsReference (&$form) {
  $settings = $form->getVar('_settings');
  $settings['civicaseCaseLastUpdatedNotificationLimit'] = CRM_Core_BAO_Setting::SYSTEM_PREFERENCES_NAME;

  $form->setVar('_settings', $settings);
}

/**
 * Replaces the date column type on case lists so it displays an alert when the
 * given date is overdue.
 *
 * @param $angular AngularManager
 */
function _civicaseextras_alterAngular_addVisualAlert (AngularManager &$angular) {
  $changeSet = AngularChangeSet::create('display_warning_for_overdue_cases')
    ->alterHtml('~/civicase/case/list/directives/case-list-table.directive.html',
      function (phpQueryObject $doc) {
        $caseListTableHtml = _civicaseextras_getTemplateContent('CRM/Civicaseextra/Partials/CaseListTable.tpl');

        $doc->find('[ng-switch-when="date"]')
          ->html($caseListTableHtml);
      });

  $angular->add($changeSet);
}

/**
 * Appends the case outcomes to the case details summary.
 *
 * @param $angular AngularManager
 */
function _civicaseextras_alterAngular_appendOutcomePanel (AngularManager &$angular) {
  $changeSet = AngularChangeSet::create('inject_case_outcomes')
    ->alterHtml('~/civicase/case/details/summary-tab/case-summary-custom-data.html',
      function (phpQueryObject $doc) {
        $doc->find('civicase-masonry-grid')
          ->prepend('<civicase-extras-case-outcome case="item"></civicase-extras-case-outcome>');
      });
  $angular->add($changeSet);
}

/**
 * Returns the HTML generated by the smarty template located at the given path.
 *
 * @param string $templatePath the path tot he smarty template.
 * @param array $vars the list of vars and their values to pass to the template.
 *
 * @return string
 */
function _civicaseextras_getTemplateContent ($templatePath, $vars = []) {
  $smarty = &CRM_Core_Smarty::singleton();

  return $smarty->fetchWith($templatePath, $vars);
}
